[project]
name = "midibox"
version = "1.0.0"
dependencies = [
	"mido",
	"netifaces",
	"python-dispatch",
	"python-osc",
	"python-rtmidi",
	"pyyaml",
	"zeroconf",
]

[project.optional-dependencies]
gui = [
	"PyQt6",
	"PyQt6-Charts",
	"PyQt6-WebEngine",
	"qasync",
]

types = [
	"types-pyyaml",
]

[project.scripts]
midibox = "midibox.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["midibox"]

[[tool.mypy.overrides]]
module = "pydispatch,mido,schema,qasync,schema,netifaces,PyQt6.QtWebEngineQuick,sip"
ignore_missing_imports = true
